# Change these first
owner: teknologi-pendidikan
repo: uptime-robot

sites:
  - name: Main Sites
    url: https://teknologipendidikan.or.id
  - name: LOFI-TEP
    url: https://lofi.um.teknologipendidikan.or.id
  - name: Hima UM
    url: https://hima.um.teknologipendidikan.or.id
  - name: Status Page
    url: https://teknologi-pendidikan.github.io/uptime-robot/

status-website:
  cname: status.sistem.teknologipendidikan.or.id
  # baseUrl: /uptime-robot
  logoUrl: https://avatars.githubusercontent.com/u/74242819?s=200&v=4
  name: Teknologi Pendidikan System Status
  introTitle: "TeknoTEP Infrastructure Status"
  introMessage: If something happens, you will know it from here
  navbar:
    - title: Status
      href: /
    - title: GitHub
      href: https://github.com/$OWNER/$REPO

# Upptime also supports notifications, assigning issues, and more
# See https://upptime.js.org/docs/configuration
